<?xml version="1.0" ?>
<testsuite name="TestNotebook-20231222005437" tests="4" time="0.000" failures="0" errors="1">
	<testcase classname="TestNotebook" name="test_add" time="0.000"/>
	<testcase classname="TestNotebook" name="test_del" time="0.000"/>
	<testcase classname="TestNotebook" name="test_err" time="0.000"/>
	<testcase classname="TestNotebook" name="test_display" time="0.000">
		<error type="AssertionError" message="'Note 1:\nTitle: Заголовок 1\nContent: Вм[90 chars]--\n' != &quot;Note 1:\nTitle: Заголовок 1\nContent: 'В[94 chars]--\n&quot;
  Note 1:
  Title: Заголовок 1
- Content: Вміст нотатка 1
+ Content: 'Вміст нотатка 1'
?          +               +
  ----------
  Note 2:
  Title: Заголовок 2
- Content: Вміст нотатка 2
+ Content: 'Вміст нотатка 2'
?          +               +
  ----------
"><![CDATA[Traceback (most recent call last):
  File "c:\programme\unik 23-24\jenkins\lab2_test.py", line 33, in test_display
    self.assertEqual(output, expected_output)
AssertionError: 'Note 1:\nTitle: Заголовок 1\nContent: Вм[90 chars]--\n' != "Note 1:\nTitle: Заголовок 1\nContent: 'В[94 chars]--\n"
  Note 1:
  Title: Заголовок 1
- Content: Вміст нотатка 1
+ Content: 'Вміст нотатка 1'
?          +               +
  ----------
  Note 2:
  Title: Заголовок 2
- Content: Вміст нотатка 2
+ Content: 'Вміст нотатка 2'
?          +               +
  ----------

]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
